language: python
sudo: required
python:
  - "2.7"
  - "3.4"
install:
   - pip install -r requirements.txt

script:

  - python -m unittest PersonTest.Test

notifications:
  email:
    - yanivomc@gmail.com


